# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Swaraj Renghe
tagline:             ''
description:         'Research Student at IIIT Hyderabad'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Swaraj Renghe
  url:               
  email:             

# Custom vars
version:             1.0.0
